server.error.include-message=never
server.error.include-binding-errors=never

# --- CONFIGURAÇÕES DO MYSQL ---
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:lamar}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:senha1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=never
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=true
# ------------------------------

logging.level.org.springframework.security=WARN

jwt.validity=${JWT_VALIDITY:3600}

COOKIE_SECURE=false

# Chave secreta do JWT (necessita de pelo menos 32 caracteres)
jwt.secret=${JWT_SECRET:minhaChaveSecretaMuitoSeguraComMaisDe32Caracteres12345}

# JavaMailSender configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:seu_email@gmail.com}
spring.mail.password=${MAIL_PASSWORD:sua_senha_de_app_aqui}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2 TLSv1.3

security.login.max-failed-attempts=${LOGIN_MAX_FAILED_ATTEMPTS:5}
security.login.lock-duration-minutes=${LOGIN_LOCK_DURATION_MINUTES:10}